[package]
name = "libnu"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "desktop/",
    "io/",
    "ktypes/",
    "mem/",
]

[dependencies]
# Workspace
desktop = { path = "desktop/" }
io = { path = "io/" }
ktypes = { path = "ktypes/" }
mem = { path = "mem/" }
# Dependencies
rlibc = "1.0.0"
uefi-graphics = { git = "https://github.com/NathanMcMillan54/uefi-graphics" }
