[package]
name = "libnu"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "desktop/",
]

[dependencies]
desktop = { path = "desktop/" }
